Controllers/BloodBankController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BloodProject.Controllers
{
    public class BloodBankController : Controller
    {
        // GET: Layout
        public ActionResult BBLayout()
        {
            return View();
        }

        public ActionResult AboutUs()
        {
            return View();
        }
    }
}

Controllers/MainController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using BloodProject.Models;
using BloodProject.Security;

namespace BloodProject.Controllers
{
    public class MainController : Controller
    {
        // GET: Main

        public ActionResult Login()
        {
            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Login(Registration model)
        {
            try
            {
                string decodeString = Encryption.encode(model.Password);
                using (var context = new BloodsDatabaseEntities())
                {
                    bool isValid = context.Registrations.Any(x => x.Email == model.Email && x.Password == decodeString);
                    if (isValid)
                    {
                        FormsAuthentication.SetAuthCookie(model.Email, false);
                        Registration r = context.Registrations.Where(x => x.Email == model.Email).FirstOrDefault();

                        TempData["a"] = r.Name;
                        TempData["b"] = r.Email;
                        TempData["c"] = r.Mobile;
                        TempData["d"] = r.BloodGroup;
                        TempData["e"] = r.Address;
                        TempData["f"] = r.Gender;
                        TempData["g"] = r.Height;
                        TempData["h"] = r.Password;
                        TempData["i"] = r.Weight;
                        TempData["j"] = r.Age;
                        TempData["k"] = r.Id;
                        return RedirectToAction("UserMainPage", "UserPage");//HERE WE CAN CHANGE INTO ADMIN OR USER LOGIN PAGE
                    }
                    ModelState.AddModelError("", "Invalid Email Or Password");

                    return View();
                }
            }
            catch
            {
                return View();
            }


        }

        public ActionResult Signup()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Signup(Registration reg)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    reg.Password = Encryption.encode(reg.Password);
                    reg.CPassword = Encryption.encode(reg.CPassword);
                    using (var context = new BloodsDatabaseEntities())
                    {
                        if (context.Registrations.Any(x => x.Email == reg.Email))
                        {
                            ViewBag.Msg = "This account has already existed";
                            return View();
                        }
                        else
                        {
                            context.Registrations.Add(reg);
                            context.SaveChanges();
                            ViewBag.Msg = "You are registred Successfully";


                            return View();

                        }
                    }

                }
                else
                {
                    return View();
                }
            }
            catch
            {
                return View();
            }

        }

        public ActionResult Logout()
        {
            try
            {
                FormsAuthentication.SignOut();
                Session.Abandon();
                return RedirectToAction("Login");
            }
            catch
            {
                return View();
            }

        }
    }
}

Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
    <script type="text/javascript">
        function ConfirmationDialog() {
            if (confirm("Are you sure to Logout?"))
                return true;
            else
                return false;
        }
    </script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Seekers", "#", new { area = "" }, new { @class = "navbar-brand", @readonly = "readonly" })

            </div>
            <div class="collapse navbar-collapse" id="myNavbar">
                <ul class="nav navbar-nav navbar-right" !important">
                    @if (User.Identity.IsAuthenticated)
                    {

                        <li>@Html.ActionLink("Queries", "Index", "AdminPage")</li>
                        <li> @Html.ActionLink("Logout", "Logout", "Main", null, new { onclick = "return ConfirmationDialog()" })</li>




                    }
                    else
                    {
                        <li>@Html.ActionLink("Login", "Login", "Main")</li>
                    }


                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">

        @RenderBody()

    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
    <script type="text/javascript">
        function ConfirmationDialog() {
            if (confirm("Are you sure to Logout?"))
                return true;
            else
                return false;
        }
    </script>
  
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @*@Html.ActionLink("Seekers", "#", new { area = "" }, new { @class = "navbar-brand" ,@readonly="readonly"})*@
                <b class="navbar-brand" style="margin-left:-190px; color:white; font-size:26px;">SEEKERS</b>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav navbar-right" !important" style="margin-right:-145px; color:white">
                    @if (User.Identity.IsAuthenticated)
                    {
                        <li><a>Dear - @User.Identity.Name</a></li>
                        <li>@Html.ActionLink("My Profile", "ProfDetails", "UserPage")</li>
                        <li>@Html.ActionLink("Check Status", "ApprovalStatus", "UserPage")</li>
                        <li>@Html.ActionLink("ContactUs", "ContactUs", "UserPage")</li>
                        <li> @Html.ActionLink("Logout", "Logout", "Main", null, new { onclick = "return ConfirmationDialog()" })</li>

                    }
                    else
                    {

                        <li style="margin-right: -10px;color:white">@Html.ActionLink("About Us", "AboutUs", "BloodBank")</li>
                        <li style="margin-right: -50px; color: white ">@Html.ActionLink("Login", "Login", "Main")</li>



                    }

                    @*<li>Login</li>*@
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">

        @RenderBody()

    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>